# Generated by Django 4.2.8 on 2023-12-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("temperature", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latitude", models.IntegerField()),
                ("longitude", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("location", models.CharField(max_length=255, unique=True)),
                ("study_PI", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VariableData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("study", models.CharField(max_length=255)),
                ("variable_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("climate_data", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Variable Data",
            },
        ),
    ]
