# Generated by Django 4.2.8 on 2023-12-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_variabledata_climate_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatedata",
            name="location",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.location"),
        ),
    ]
