# Generated by Django 4.2.8 on 2023-12-22 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_climatedata_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variabledata",
            name="variable_name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.variable"),
        ),
    ]
